function y = highpassNoiseFilter(x)
%HIGHPASSNOISEFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 13-Apr-2016 07:15:32

persistent Hd;

if isempty(Hd)
    
    Fstop = 3.8;   % Stopband Frequency
    Fpass = 4.6;   % Passband Frequency
    Astop = 60;    % Stopband Attenuation (dB)
    Apass = 3;     % Passband Ripple (dB)
    Fs    = 16;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'kaiserwin');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


