function y = highhighFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 11-Apr-2016 20:50:14

persistent Hd;

if isempty(Hd)
    
    Fstop = 5500;   % Stopband Frequency
    Fpass = 5700;   % Passband Frequency
    Astop = 60;     % Stopband Attenuation (dB)
    Apass = 1;      % Passband Ripple (dB)
    Fs    = 16000;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

