function y = lowFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 11-Apr-2016 20:46:02

persistent Hd;

if isempty(Hd)
    
    Fpass = 3600;   % Passband Frequency
    Fstop = 3800;   % Stopband Frequency
    Apass = 1;      % Passband Ripple (dB)
    Astop = 60;     % Stopband Attenuation (dB)
    Fs    = 16000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

